# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CBGKLZOlUo4GVPXN176CUhKO_7HqLrA
"""

import streamlit as st
import altair as alt
from match_insights import load_and_clean_data, generate_insights

st.title("CricHeroes: IPL Match Insight Generator")

# Load and compute season stats from single CSV
df, batting_stats_unique, bowling_stats_unique = load_and_clean_data("ipl_ball_by_ball.csv")

match_ids = df['match_id'].unique()
selected_match = st.selectbox("Select Match ID", match_ids)

if selected_match:
    insights, batting_phase, bowling_phase, batting_merge, bowling_merge = generate_insights(
        df, batting_stats_unique, bowling_stats_unique, selected_match
    )

    st.subheader("Player Insights")
    for s in insights:
        st.write(s)

    # ------------------------------
    st.subheader("Batting Phase-wise Metrics")
    st.dataframe(batting_phase)

    st.subheader("Bowling Phase-wise Metrics")
    st.dataframe(bowling_phase)

    # ------------------------------
    st.subheader("Top 5 Batting PPI Players")
    top_bat = batting_merge.sort_values('PPI', ascending=False).head(5)
    chart_bat = alt.Chart(top_bat).mark_bar().encode(
        x=alt.X('striker', sort='-y'),
        y='PPI',
        color='striker'
    )
    st.altair_chart(chart_bat, use_container_width=True)

    st.subheader("Top 5 Bowling PPI Players")
    top_bowl = bowling_merge.sort_values('PPI', ascending=False).head(5)
    chart_bowl = alt.Chart(top_bowl).mark_bar().encode(
        x=alt.X('bowler', sort='-y'),
        y='PPI',
        color='bowler'
    )
    st.altair_chart(chart_bowl, use_container_width=True)