# -*- coding: utf-8 -*-
"""match_insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uN4_g3pB9pppQBUHqxWZJlSGn68qys7v
"""

import pandas as pd

def load_and_clean_data(ball_by_ball_path):
    df = pd.read_csv(ball_by_ball_path)

    # ----- Compute season aggregates dynamically -----
    batting_stats_unique = df.groupby(['season','striker']).agg(
        avg_runs=('runs_of_bat','mean'),
        strike_rate=('runs_of_bat','sum')/('legal_ball','sum')*100  # simplified strike rate
    ).reset_index()

    bowling_stats_unique = df.groupby(['season','bowler']).agg(
        wickets=('player_dismissed','count'),
        runs_conceded=('runs_of_bat','sum'),
        balls_bowled=('legal_ball','sum')
    ).reset_index()
    bowling_stats_unique['economy'] = bowling_stats_unique['runs_conceded']/ (bowling_stats_unique['balls_bowled']/6)

    return df, batting_stats_unique, bowling_stats_unique

# ------------------------------
# 2️⃣ Generate insights per match
# ------------------------------
def generate_insights(df, batting_stats_unique, bowling_stats_unique, match_id):
    match_rows = df[df['match_id'] == match_id].copy()
    match_season = match_rows['season'].iloc[0]

    # Phase-wise flag
    def phase(over):
        if 1 <= over <= 6: return 'Powerplay'
        elif 7 <= over <= 15: return 'Middle'
        else: return 'Death'
    match_rows['phase'] = match_rows['over'].apply(phase)

    # ----- Batting aggregation -----
    batting_match = match_rows.groupby('striker').agg(
        runs_match=('runs_of_bat','sum'),
        balls_match=('legal_ball','sum'),
        dot_balls=('dot_ball','sum'),
        boundaries=('boundary','sum')
    ).reset_index()
    batting_match['strike_rate_match'] = batting_match['runs_match']/batting_match['balls_match']*100
    batting_match['dot_ball_pct_match'] = batting_match['dot_balls']/batting_match['balls_match']*100
    batting_match['boundary_pct_match'] = batting_match['boundaries']/batting_match['balls_match']*100

    # Merge with season stats
    batting_merge = pd.merge(
        batting_match,
        batting_stats_unique[batting_stats_unique['season']==match_season],
        on='striker',
        how='left'
    )

    # ----- Bowling aggregation -----
    bowling_match = match_rows.groupby('bowler').agg(
        balls_bowled=('legal_ball','sum'),
        runs_conceded=('runs_of_bat','sum'),
        wickets=('player_dismissed','count'),
        dot_balls=('dot_ball','sum')
    ).reset_index()
    bowling_match['overs'] = bowling_match['balls_bowled']/6
    bowling_match['economy'] = bowling_match['runs_conceded']/bowling_match['overs']

    bowling_merge = pd.merge(
        bowling_match,
        bowling_stats_unique[bowling_stats_unique['season']==match_season],
        on='bowler',
        how='left'
    )

    # ----- PPI -----
    batting_merge['PPI'] = batting_merge['runs_match']*0.5 + batting_merge['strike_rate_match']*0.3 - batting_merge['dot_ball_pct_match']*0.2
    bowling_merge['PPI'] = bowling_merge['wickets']*1.0 - bowling_merge['economy']*0.5 + bowling_merge['dot_balls']*0.2

    # ----- Insights -----
    insights = []

    for _, row in batting_merge.iterrows():
        sentences = []
        if row['strike_rate_match'] > row['strike_rate_season']:
            sentences.append(f"{row['striker']} scored at a strike rate of {row['strike_rate_match']:.1f}, above his season average of {row['strike_rate_season']:.1f}.")
        else:
            sentences.append(f"{row['striker']}'s strike rate was {row['strike_rate_match']:.1f}, slightly below his season average of {row['strike_rate_season']:.1f}.")

        if row['runs_match'] > row['avg_runs_season']:
            sentences.append(f"He scored {row['runs_match']} runs, higher than his season average of {row['avg_runs_season']:.1f}.")
        else:
            sentences.append(f"He scored {row['runs_match']} runs, slightly below his season average of {row['avg_runs_season']:.1f}.")

        sentences.append(f"(PPI: {row['PPI']:.1f})")
        insights.append(" ".join(sentences))

    for _, row in bowling_merge.iterrows():
        sentences = []
        if row['economy'] < row['economy_season']:
            sentences.append(f"{row['bowler']} bowled economically at {row['economy']:.2f}, better than his season average of {row['economy_season']:.2f}.")
        else:
            sentences.append(f"{row['bowler']}'s economy was {row['economy']:.2f}, slightly above his season average.")

        sentences.append(f"He took {row['wickets']} wickets. (PPI: {row['PPI']:.1f})")
        insights.append(" ".join(sentences))

    return insights